EventDispatcherTest: avoid persistent state, improve naming.
Use local functions and variables versus members, mimicing existing tests.

Test semantics mostly unchanged; some minor changes to the second test's remove/add order.  Failures and successes for all platforms remain the same... except:

AS3 is now additionally failing post this commit:

Failure: testDispatchingRemainsTrue (0.001s)
massive.munit.AssertionException: Value [a(abc)c] was not equal to expected value [a(abc)bc] at openfl.events.EventDispatcherTest#testDispatchingRemainsTrue (310)

...ugh.  This means that Flash Player / AS3 isn't guaranteed to not mutate the in-flight dispatch list.  Not sure what to do about this...